name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the base image
        run: make base_image

  build_generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network generic image
        run: make generic_image && docker inspect --type=image $(make get_generic_image) > /dev/null

  build_generic_jfrog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network generic jfrog image
        run: make generic_jfrog_image && docker inspect --type=image $(make get_generic_jfrog_image) > /dev/null

  build_gui_kali:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network GUI Kali image
        run: make gui_debian_kali && docker inspect --type=image $(make get_gui_kali_image) > /dev/null

  build_gui_debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network GUI Debian image
        run: make gui_debian && docker inspect --type=image $(make get_gui_debian_image) > /dev/null

  build_gui_ubuntu_base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network GUI Ubuntu base image
        run: make gui_ubuntu_base_image && docker inspect --type=image $(make get_gui_ubuntu_base_image) > /dev/null

  build_gui_ubuntu_eclipse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network GUI Ubuntu Eclipse image
        run: make gui_ubuntu_eclipse_image && docker inspect --type=image $(make get_gui_ubuntu_eclipse_image) > /dev/null

  build_ubuntu18_base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network Ubuntu18 Image
        run: make base18_image && docker inspect --type=image $(make get_base18_image) > /dev/null

  build_centos_base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network CentOS Image
        run: make centos_base_image && docker inspect --type=image $(make get_centos_base_image) > /dev/null
        
  build_minimal_alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network Minimal Alpine image
        run: make minimal_alpine_image && docker inspect --type=image $(make get_minimal_alpine_image) > /dev/null

  build_minimal_rhel9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network Minimal RHEL9 image
        run: make minimal_rhel9_image && docker inspect --type=image $(make get_minimal_rhel9_image) > /dev/null
