name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_base:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the base image
      run: make base_image
  
  build_golang:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Build strong network golang image
        run: make golang_image && docker inspect --type=image ${make get_golang_image}