name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the base image
      run: make base_image
  
  build_golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network golang image
        run: make golang_image && docker inspect --type=image $(make get_golang_image) > /dev/null

  build_golang_1_17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network golang_1.17 image
        run: make golang_1.17_image && docker inspect --type=image $(make get_golang_1.17_image) > /dev/null

  build_flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network flutter
        run: make flutter_image && docker inspect --type=image $(make get_flutter_image) > /dev/null
  
  build_python_spark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network python spark image 
        run: make python_spark_image && docker inspect --type=image $(make get_spark_image) > /dev/null

  build_python_datascience:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network python datascience image 
        run: make python_datascience_image && docker inspect --type=image $(make get_python_datascience_image) > /dev/null

  build_python_anaconda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network python anaconda image 
        run: make python_anaconda_image && docker inspect --type=image $(make get_python_anaconda_image) > /dev/null

  build_nodejs_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network nodejs iamge 
        run: make nodejs_image && docker inspect --type=image $(make get_nodejs_image) > /dev/null
  
  build_generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network generic image
        run: make generic_image && docker inspect --type=image $(make get_generic_image) > /dev/null

  build_java_intellij:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network java with intellij image
        run: make java_intellij && docker inspect --type=image $(make get_java_intellij_image) > /dev/null

  build_goland:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network java with intellij image
        run: make goland && docker inspect --type=image $(make get_goland_image) > /dev/null

  build_pycharm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Build strong network pycharm image
        run: make pycharm && docker inspect --type=image $(make get_pycharm_image) > /dev/null

  build_phpstorm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network phpstorm image
        run: make phpstorm && docker inspect --type=image $(make get_phpstorm_image) > /dev/null
  
  build_android_studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network android studio image
        run: make android_studio && docker inspect --type=image $(make get_android_studio_image) > /dev/null

  build_webstorm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build strong network webstorm image
        run: make webstorm_image && docker inspect --type=image $(make get_webstorm_image) > /dev/null