name: Push images to AWS ECR

on:
  workflow_dispatch:

jobs:
  deploy_images:
    environment: production
    env:
      REGISTRY_URL: ${{ secrets.AWS_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get image url
        run: |
          GIT_ROOT=$(git rev-parse --show-toplevel)
          VERSION=$(awk NF ${GIT_ROOT}/VERSION)
          echo GENERIC_IMAGE_URL=$REGISTRY_URL/cloud_editor_generic:$VERSION >>  $GITHUB_ENV
          echo JFROG_GENERIC_IMAGE_URL=$REGISTRY_URL/jfrog_generic:$VERSION >>  $GITHUB_ENV
          echo SYSBOX_GENERIC_IMAGE_URL=$REGISTRY_URL/sysbox_generic:$VERSION >> $GITHUB_ENV
          echo GUI_DEBIAN_KALI_IMAGE_URL=$REGISTRY_URL/gui_debian_kali_linux:$VERSION >> $GITHUB_ENV
          echo GUI_UBUNTU_BASE_IMAGE_URL=$REGISTRY_URL/gui_ubuntu_base:$VERSION >> $GITHUB_ENV
          echo GUI_UBUNTU_ECLIPSE_IMAGE_URL=$REGISTRY_URL/gui_ubuntu_eclipse:$VERSION >> $GITHUB_ENV

          echo GENERIC_IMAGE_NAME=$(make get_generic_image) >> $GITHUB_ENV
          echo SYSBOX_GENERIC_IMAGE_NAME=$(make get_sysbox_generic_image) >> $GITHUB_ENV
          echo GUI_DEBIAN_IMAGE_NAME=$(make get_gui_debian_image) >> $GITHUB_ENV
          echo GUI_UBUNTU_BASE_IMAGE_NAME=$(make get_gui_ubuntu_base_image) >> $GITHUB_ENV
          echo GUI_UBUNTU_ECLIPSE_IMAGE_NAME=$(make get_gui_ubuntu_eclipse_image) >> $GITHUB_ENV
          echo JFROG_GENERIC_IMAGE_NAME=$(make get_generic_jfrog_image) >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build the base image
      - name: Build the base image
        run: make base_image

      - uses: ./.github/actions/push-image
        name: push generic image
        with:
          image-name: ${{ env.GENERIC_IMAGE_NAME }}
          make-command: generic_image
          image-url: ${{ env.GENERIC_IMAGE_URL }}

      - uses: ./.github/actions/push-image
        name: push gui debian kali image
        with:
          image-name: ${{ env.GUI_DEBIAN_IMAGE_NAME }}
          make-command: gui_debian
          image-url: ${{ env.GUI_DEBIAN_KALI_IMAGE_URL }}

      - uses: ./.github/actions/push-image
        name: push gui ubuntu base image
        with:
          image-name: ${{ env.GUI_UBUNTU_BASE_IMAGE_NAME }}
          make-command: gui_ubuntu_base_image
          image-url: ${{ env.GUI_UBUNTU_BASE_IMAGE_URL }}

      - uses: ./.github/actions/push-image
        name: push gui ubuntu eclipse image
        with:
          image-name: ${{ env.GUI_UBUNTU_ECLIPSE_IMAGE_NAME }}
          make-command: gui_ubuntu_eclipse_image
          image-url: ${{ env.GUI_UBUNTU_ECLIPSE_IMAGE_URL }}

      - uses: ./.github/actions/push-image
        name: push generic image JFROG
        with:
          image-name: ${{ env.JFROG_GENERIC_IMAGE_NAME }}
          make-command: generic_jfrog_image
          image-url: ${{ env.JFROG_GENERIC_IMAGE_URL }}

      - uses: ./.github/actions/push-image
        name: push sysbox image
        with:
          image-name: ${{ env.SYSBOX_GENERIC_IMAGE_NAME }}
          make-command: generic_sysbox_image
          image-url: ${{ env.SYSBOX_GENERIC_IMAGE_URL }}